### ISSUE TITLE
PDF 版 P.134 と P.140 の脚注のリンクがおかしい

### ISSUE THREAD

**Issue by kariya-mitsuru** [shellgei/shellgei160#10]
PDF 版 P.134 脚注
注 12 のマニュアルのリンクが『[https://docs.ruby-lang.org/ja/latest/doc/spec=2fregexp.html」にあります。](https://docs.ruby-lang.org/ja/latest/doc/spec=2fregexp.html%E3%80%8D%E3%81%AB%E3%81%82%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82)』になってしまっています。（『」にあります』までリンクになっている）

PDF 版 P.140 脚注
注 16 のリンクが『[https://docs.ruby-lang.org/ja/latest/docspec=2fregexp.html](https://docs.ruby-lang.org/ja/latest/docspec=2fregexp.html)』になってしまっています。（doc と spec の間に / が必要）

**Comment by ryuichiueda** [comment]
出版社の人にお伝えしますー。ありがとうございます。

**Comment by ryuichiueda** [comment]
メモ: とりあえずpdfが直るか正誤表に記載されるかまでopenで。

**Comment by ryuichiueda** [comment]
技術評論社さんから回答がありました。次のような対応になります。ありがとうございました。

### PDF 版 P.134 脚注

こちらはPDFを修正するとのことです。

### PDF版 P.140 脚注

こちらは紙版もまちがっており、紙版の増刷のタイミングで、電子版も修正とのことです。

**Comment by ryuichiueda** [comment]
p.140の修正を正誤表に加えました。

https://github.com/shellgei/shellgei160/blob/master/README.md

**Comment by ryuichiueda** [comment]
紙版が第3刷になったので確認しました。が・・・

* p.134: リンクがなおってない！
* p.140: 文面はなおったけどリンクはなおってない！

ということで、たぶん担当者にちゃんと伝わってなくて著者としても忸怩たる思いなのですが、4刷に向けてがんばります・・・

**Comment by ryuichiueda** [comment]
@papiron さんが現在のpdfを確認したところ、修正されていたそうです。closeします。
