### ISSUE TITLE
kindle書籍において`\\`となるべき場所が`\`に置き換わっている箇所がある

### ISSUE THREAD

**Issue by origamium** [shellgei/shellgei160#2]
書籍詳細: Amazonで購入したkindle電子書籍（最終頁では初版 第一刷発行表記）

書籍に載っている問題3別解1は

```sh
time find . | sed 's;^\./;;' | grep -v ^\.$ | grep -v ^0 | awk '{print $1,sprintf("%07d",$1)}' | xargs -n2 -P2 mv
```

となっています。しかしこのコードは0から9までの数字を無視してしまうので期待した動作になりませんでした。ただ、[github上](https://github.com/shellgei/shellgei160/blob/master/answer/3.md)の別解1

```sh
time find . | sed 's;^\./;;' | grep -v ^0 | awk '{print $1,sprintf("%07d",$1)}' | xargs -n2 -P2 mv
```
が正しい動きをしていたので報告します。

ただこちらもmacOSとamazonlinuxの両方で試したのですが、`mv . 0000000`を走らせるような挙動をするので、

```sh
time find . | sed 's;^\./;;' | grep -v ^\\. | awk '{print $1,sprintf("%07d",$1)}' | xargs -n2 -P2 mv
```

の方がエラーが起きないので好きです。

**Comment by ryuichiueda** [comment]
ありがとうございます。私の持っている原稿ですと、`grep -v ^\.$`のところは、`grep -v ^\\.$`とバックスラッシュが2つになっています。これでもうまくいかないでしょうか。ご確認をおねがいいたします。

**Comment by origamium** [comment]
うまくいきました！ありがとうございます。ただ書籍の方もう一度確認しましたが当該のバックスラッシュは1個のままでした

**Comment by greymd** [comment]
動きとしては正しかったものの、本リポジトリの問題3の別解1が書籍版のものと一部異なっていたため、下記のように修正しました。ありがとうございます。
https://github.com/shellgei/shellgei160/pull/3/files

ご購入いただいたKindle版のバックスラッシュが1個だった、という点に関しては確認中です。

**Comment by greymd** [comment]
確認をしたところ、電子書籍版ではコードブロック中の `\\` が `\` になっている箇所が複数確認されました。
紙の書籍の場合にはそのような状況ではないようです。

こちらについては、出版社の担当に報告をさせていただきます。
今後、正誤表の用意ないし改訂版の配信など、対応を検討をする流れになるかと思います。

お手数ですが、直近では GitHub 上の answer を適宜確認しつつ読み進めていただけると幸いです。
下記の問題番号に `\\` が確認されておりますため、お気をつけください（ネタバレにならないよう解答部分は隠しています）。

```
$ grep '\\\\' * | grep -oP '^.*?\$' | sed 's/.md//;s/^/問題/'
問題3:別解1（上田）$
問題20:別解2（上田）$
問題36:別解1（中村）$
問題38:別解1（山田）$
問題39:別解5（山田）$
問題51:別解2（山田）$
問題55:別解2（上杉）$
問題74:$
問題83:$
問題84:解答2（青木）$
問題84:解答5（田代）$
問題101:別解2（eban）$
問題129:$
問題135:別解1（山田）$
問題138:別解2（中村）$
問題147:$
```

なお、練習問題では 練習3.2.a、練習3.2c のコードブロックにて `\\` が確認がされています。
オフィシャルな正誤表ではありませんが、一旦、下記のように読み替えてください。

##### 練習3.2.a
訂正前:`s/./&\n?/g`
訂正後:`s/./&\\n?/g`

##### 練習3.2.c
訂正前: `tr -d \n`
訂正後: `tr -d \\n`

**Comment by ryuichiueda** [comment]
@origamium ありがとうございます。結構大きなご指摘でした。

**Comment by papiron** [comment]
電子書籍の第3刷について、Kindle版、pdf版、epub版とも、修正されていることを確認しました。
この件クローズしますね。
