### ISSUE TITLE
PDF 版 P.247～248（問題 74）に誤植がある（多分）

### ISSUE THREAD

**Issue by kariya-mitsuru** [shellgei/shellgei160#23]
P.247 問題 リスト 5.3
3 行目が「2020年1月1日」になっていますが、その後の結果や GitHub のファイルを見ると「2020年8月1日」が正しいように見えます。

P.248 解答
1 段目の awk の printf の引数の最後に「,$0」が付いていますが、書式と合っていません。
（付いていても正しい答えが得られますが…）
なお、GitHub の解答にも「,$0」が付いていますが、解説には付いていません。

**Comment by ryuichiueda** [comment]
こちら遅くなりましたが正誤表への追加とリポジトリの解答例の訂正を行いました。ありがとうございました。
