### ISSUE TITLE
PDF 版 P.266（問題 82 の解説）に誤植がある

### ISSUE THREAD

**Issue by kariya-mitsuru** [shellgei/shellgei160#27]
問題 82 解説の 2 番目で、コマンドが
```
split -b 1000 -d image.bmp image.bmp.
```
になっていますが、出力のサフィックスは `aa` とかになっていて矛盾しています。

コマンドから `-d` オプションを取るか、出力のサフィックスを数字にする必要があります。
（`-d` の説明が無いので、コマンドから取った方が良さそう…）

**Comment by ryuichiueda** [comment]
ダイジョウブでーす
