### ISSUE TITLE
UTF-32BE について

### ISSUE THREAD

**Issue by kariya-mitsuru** [shellgei/shellgei160#28]
単なるコメントも歓迎と言って頂けたので…

PDF 版 P.259 に

> ただ、逆に高い桁から記録する場合、BOMが`0000feff`となるのですが、上の出力のように、`iconv`はBOMを付けてくれません。

との記載があります。

この記載だと何となく `iconv` が不親切な印象を受けてしまうので、以下のような記載の方が望ましい気がしました。

> ただ、逆に高い桁から記録する場合、BOMが付くとすれば`0000feff`となるはずですが、上の出力のように`UTF-32BE`ではBOMは付きません。

仕様として`UTF-32BE`にはBOMは存在せず、仮に先頭に`0000feff`が存在してしまうと本来の意味である zero width no-break space（ZWNBSP）と解釈されてしまいます（仕様にも明記されている）。

ちなみに、BOM 付き UTF-8（？）を `iconv` で `UTF-32` に変換してみたところ UTF-8 の先頭は ZWNBSP と解釈されるようで、先頭は `0000feff 0000feff` になってしまうようです（これに関連した記載も仕様に記載されている）。

個人的には BOM 付き UTF-8 なるナゾなものは別のエンコーディングスキーム名を割り当てるべきだと思うんですけど…

**Comment by ryuichiueda** [comment]
ありがとうございます。調査不足でした。次の版で脚注を入れるかもしれません。READMEにこのissueのリンクを張りました。一旦クローズで。
