### ISSUE TITLE
[問題4] mac環境でRANDOMを利用すると全て同じ値になる

### ISSUE THREAD

**Issue by lirlia** [shellgei/shellgei160#30]
自分の環境の二種類のmacで試してみましたが失敗したので念の為issue化しておきます。
※書籍自体がmac対応ではなかったと思うので不要ならクローズください

以下のコマンドを実行して作成されるファイル100個が全て同じ値になります。

```
seq 100 | sed "s/^/echo $RANDOM > /" | bash
```

**Comment by greymd** [comment]
記載いただいたコマンドのダブルクォーテーション `"` をシングルクォーテーション `'` にしたら動作はどうなりますかね？

```
seq 1000000 | sed 's/^/echo $RANDOM > /' | bash
```

このコマンドは`echo $RANDOM > 数字`というシェルスクリプトを`bash`コマンドに与えて、改めてスクリプトとして再実行してファイルを作成します。
この個所が、ダブルクォーテーションだと`bash`に与えられる前に`$RANDOM`の内容が数字に置き換えられてしまい、特定の値が使われてしまいますね。
なお、書籍上はシングルクォーテーション`'`にしているはずです。

ダブルクォーテーションとシングルクォーテーションの違いについては、PDFや書籍版であれば、p.61 に説明がございますのでご参照ください。macOSでもこちらは動作すると思います。🙇 

その他何か想定しない動作があれば引き続きお気軽に Issue たてていただければ。

**Comment by lirlia** [comment]
なるほどそういうことなんですね！失礼いたしました（確かに動作しました！）
わざわざありがとうございます！
