### ISSUE TITLE
P44　問題６について

### ISSUE THREAD

**Issue by motimotinoyamayama** [shellgei/shellgei160#39]
初めて質問させていただきます。

P44　問題６について、解答も確認しましたが、理解できませんでした。
for文の解釈出来ず、インクリメント演算子も分かりません。

よろしくお願いします。

**Comment by motimotinoyamayama** [comment]
> 初めて質問させていただきます。
> 
> P44　問題６について、解答も確認しましたが、理解できませんでした。 for文の解釈出来ず、インクリメント演算子も分かりません。
> 
> よろしくお願いします。

**Comment by motimotinoyamayama** [comment]
> 初めて質問させていただきます。
> 
> P44　問題６について、解答も確認しましたが、理解できませんでした。 for文の解釈出来ず、インクリメント演算子も分かりません。
> 
> よろしくお願いします。

**Comment by ryuichiueda** [comment]
for文が解釈で着ないことに対しては直接の答えになってませんが、awkのコードを整理して、コメントを入れるとこんな感じでしょうか。

```
{
	for(i=1;i<$1;i++){  #$1にseqからの数字が入る。
		printf " "  #$1の数だけ空白が並ぶ。
	}
	print "x"           #空白のうしろにxが出力されて改行される。
}
```

**Comment by ryuichiueda** [comment]
forには「;」で3つ文を並べます。

* i=1はiを1で初期化
* iが$iになるまで繰り返す
* i++はiに1を足す

です。

**Comment by ryuichiueda** [comment]
だいたいこんなところなのですが、for文についてはつまづく人が多いので、ウェブサイトに色んな解釈が載っています。いろいろ調べて、自分が納得できる解釈で理解すればよいと思います。ひとつだけURLを書いておきます。

* https://techacademy.jp/magazine/5481

**Comment by motimotinoyamayama** [comment]
ありがとうございます。
ｆｏｒ文の解釈は出来ました。

ただprintとprintf違いが分かりません。

**Comment by ryuichiueda** [comment]
> ただprintとprintf違いが分かりません。

これは本のなかに書いてあります。たぶん索引を使うと見つけられると思います。

**Comment by motimotinoyamayama** [comment]
本の中で確認出来ました。ありがとうございました。
