### ISSUE TITLE
p30の補足（xargsのコマンドなしの用法と注意）について

### ISSUE THREAD

**Issue by physicshinzui** [shellgei/shellgei160#41]
私の環境（M1 macbbok）では、p30 の一番下に記載されている以下のコマンドの出力が教科書と異なりました：
```
$ awk 'BEGIN{print "-e 1 2 3"}' | xargs
-e 1 2 3
```
教科書では`-e`は出力されていませんが、私の環境では`-e`も出力されるようです。

**Comment by ryuichiueda** [comment]
情報ありがとうございます。Macの外部コマンドのechoには-eオプションがないものと思われます。

https://github.com/shellgei/shellgei160/issues?q=is%3Aissue+label%3Amac+ でこのissueを閲覧可能にしてありますので閉じます。
