### ISSUE TITLE
P36 convertについて（処理時間）

### ISSUE THREAD

**Issue by POCHI-CUTE** [shellgei/shellgei160#45]
別解の,
`ls *.png | sed 's/\.png//' | xargs -I@ convert @.png @.jpg`
は，私の環境では2sほどでしたが，自分で考えた回答で
`convert *.png *.jpg`
と書いたところ，48sほどかかりました．
なぜこれほど時間に差が出るのか理解できませんでした．
そもそも私の回答が間違っているのでしょうか．
初心者質問で申し訳ないですが，よろしくお願いします。

**Comment by ryuichiueda** [comment]
`convert *.png *.jpg` がどのような挙動を示すのかは分からないのですが、*.pngは「全てのpngファイル」を指してしまうので、

```
convert 10_black.png 11_steelblue.png 12_orange.png 13_yellow.png 14_blue.png 15_steelblue.png 16_steelblue.png 17_brown.png 18_orange.png 19_red.png 1_purple.png 20_brown.png 21_red.png 22_yellow.png ...
```

というコマンドが実行されていることになります。ですので、一つずつconvertする別解とは、そもそも違う命令を出していることになります。

**Comment by POCHI-CUTE** [comment]
丁寧なご回答ありがとうございます！
アスタリスクの挙動をよく分かっていませんでしたが、よくわかりました。
また、コマンドラインが楽しく学べる本をありがとうございます！
