### ISSUE TITLE
練習22の別解１（P101）での「# %g」の意味がわかる方教えていただけると助かります。

### ISSUE THREAD

**Issue by michiots** [shellgei/shellgei160#46]
練習22の別解１（P101）での「# %g」の意味が理解できずにいます。

echo にかかるものでしょうか、それとも別の意味があるのでしょうか。

**Comment by michiots** [comment]
既出の質問でした。
https://github.com/shellgei/shellgei160/issues/42

**Comment by ryuichiueda** [comment]
最後のbashをつけないでseqを実行するとわかるのですが、 「# 1」みたいにデバッグ用のコメントをつけるために使っています。（closeされましたが、書いている途中だったので投稿しておきます。）

```
$ seq -f 'echo $(grep -E "^[a-z]+$" /usr/share/dict/words|shuf -n1).$(shuf -n1 -e {com,org,{co.,}jp,net}) # %g' 100
echo $(grep -E "^[a-z]+$" /usr/share/dict/words|shuf -n1).$(shuf -n1 -e {com,org,{co.,}jp,net}) # 1
echo $(grep -E "^[a-z]+$" /usr/share/dict/words|shuf -n1).$(shuf -n1 -e {com,org,{co.,}jp,net}) # 2
・・・
```

**Comment by michiots** [comment]
コメントありがとうございます。
githubの使い方が分が分からず（ほとんど初めて）、後で既出の質問に気づきました。
ラズパイの設定とかでshellをもっと使いこなしたくて160本ノックをしています。
めげそうになるとryuichiuedaさんのyoutubeを見て元気をもらっています（笑
時間があるGW、160本ノックを進めます！

**Comment by michiots** [comment]
P76の seq -f %g の使い方に、bashに渡した時にコメントにするための ＃ ですね。
