### ISSUE TITLE
p397 問題139の解答について

### ISSUE THREAD

**Issue by Polly9** [shellgei/shellgei160#49]
`echo 'cc.bb.aa.example.com' | awk -F'.' '{s=$NR;for(i=(NF-1);i>0;i--){s=$i"."s;print s}}'`

↑解答例に$が抜けていませんか？
これだとフィールド数の5を出力してしまいますので、以下だと解答例通りの出力を得ました。環境はMacです。

`echo 'cc.bb.aa.example.com' | awk -F'.' '{s=$NR;for(i=(NF-1);i>0;i--){s=$i"."$s;print s}}'`

**Comment by ryuichiueda** [comment]
ご連絡ありがとうございます。

確認しましたが、書籍の内容でURLが出てきました。Macであっても、あるいはどのAWKでも、sという変数に$をつけることはないので、もう一度ご確認お願い致します。

**Comment by ryuichiueda** [comment]
以下、Linuxのgawkでの結果です。

```
$ echo 'cc.bb.aa.example.com' | awk -F'.' '{s=$NR;for(i=(NF-1);i>0;i--){s=$i"."s;print s}}'
example.cc
aa.example.cc
bb.aa.example.cc
cc.bb.aa.example.cc
$ echo 'cc.bb.aa.example.com' | awk -F'.' '{s=$NR;for(i=(NF-1);i>0;i--){s=$i"."$s;print s}}'
example.cc.bb.aa.example.com
aa.cc.bb.aa.example.com
bb.cc.bb.aa.example.com
cc.cc.bb.aa.example.com
```

**Comment by ryuichiueda** [comment]
あ。本はs=$NRじゃなくて、s=$NFになってます。

```
$ echo 'cc.bb.aa.example.com' | awk -F'.' '{s=$NF;for(i=(NF-1);i>0;i--){s=$i"."s;print s}}'
example.com
aa.example.com
bb.aa.example.com
cc.bb.aa.example.com
```

これがたぶん正解だと思われます。

**Comment by Polly9** [comment]
凡ミス失礼いたしました。迅速、かつ丁寧なご回答を誠にありがとうございます。こちらはクローズいたします。
コツコツやってたら残り20pほどになりました（ほんとに半年かかりました）。最後まで楽しみたいと思います。
