### ISSUE TITLE
練習2.1.e (p.61) の `~` のクォートについての記述は誤り

### ISSUE THREAD

**Issue by norioxkimura** [shellgei/shellgei160#50]
PDF 版 2022/1/1 の練習2.1.e (p.61) に「ダブルクォートによるクォートの場合、中にあるBashの変数は解釈されます。また、変数だけでなく、ホームディレクトリを表す`~`などの特殊な記号も解釈されます。」とありますが、ダブルクォート中では `~`（や `*` や `?`）は展開されないと思います。

```
$ echo ~
/home/ubuntu
$ echo "~"
~
```

**Comment by ryuichiueda** [comment]
ほんとですね・・・修正いたします。ありがとうございます！

**Comment by ryuichiueda** [comment]
とりあえず修正を掲示して、共著者に確認してもらって、私は仕様をもう一度確認中です。

https://github.com/shellgei/shellgei160/blob/master/README.md#%E7%AC%AC4%E5%88%B7%E3%81%BE%E3%81%A7

**Comment by norioxkimura** [comment]
p.113 「`~` などのメタ文字について、特別な意味を打ち消してそのまま使いたい場合は、次のようにバックスラッシュ「`\`」でエスケープするか、もしくはシングルクォート「`'`」でくくる必要があります。」
→ ダブルクォート `"` でも問題ない。

**Comment by ryuichiueda** [comment]
お、こちらもありがとうございます。修正します。

**Comment by ryuichiueda** [comment]
https://github.com/shellgei/shellgei160#%E7%AC%AC4%E5%88%B7%E3%81%BE%E3%81%A7
修正入れました。ありがとうございました。
