### ISSUE TITLE
問題26の補足２(p110)の文章２行目の「cowsey」は「cowsay」の間違いでしょうか。

### ISSUE THREAD

**Issue by michiots** [shellgei/shellgei160#51]
標題の件で質問です。
問題26の補足２(p110)の文章２行目の「cowsey」は「cowsay」の間違いでしょうか。
インターネットで検索しても出てこず、疑問に思ったので質問させて下さい。

**Comment by ryuichiueda** [comment]
あ。タイポですね。ありがとうございます。

**Comment by ryuichiueda** [comment]
修正を記載しておきました。ありがとうございました。

https://github.com/shellgei/shellgei160#%E7%AC%AC4%E5%88%B7%E3%81%BE%E3%81%A7

**Comment by michiots** [comment]
お返事ありがとうございます！
初心者には、読み進めるのに骨が折れますが、読み進められないことはないです。
この本を読むことで考え方の範囲が広がります。頑張ります！
