### ISSUE TITLE
問題 147 で `grep -P` と `grep -z` の組み合わせがうまく動かない

### ISSUE THREAD

**Issue by norioxkimura** [shellgei/shellgei160#52]
`printf '<td>\ncell</td>\n' | grep -zoP '<td[^<]*>.*?</td>'` を実行しても何も表示されない（行をまたいだ `<td>...</td>` にマッチしない）。man grep には `-P` と `-z` の組み合わせは experimental と書いてある。

Ubuntu 20.04, grep 3.4, libpcre 3.13.3

**Comment by ryuichiueda** [comment]
こちら対応おそくなってすみません。週末対応します。

**Comment by ryuichiueda** [comment]
これは間違いで-Eのほうがいいですね。修正しておきます。ありがとうございました。

**Comment by ryuichiueda** [comment]
メモ:

* 問題147はgrep -zoPが改行に対応していない
* 練習3.2.aではgrep -ozPが機能する

**Comment by ryuichiueda** [comment]
ebanさんから。「PCREだと改行が.にマッチしない」というのが理由とのこと。修正するなら↓。

```
printf '<td>\ncell</td>\n' | grep -zoP '(?s)<td[^<]*>.*?</td>'
```

**Comment by ryuichiueda** [comment]
↑ということで、ライブラリのバージョン違いと言うよりは、単なる間違いでした。しばらくしたら閉じます。

ありがとうございました。
