### ISSUE TITLE
問題73のファイル名の文字化けが再現できない

### ISSUE THREAD

**Issue by keijinozaki** [shellgei/shellgei160#53]
`$ LANG=C unzip 秘密の圧縮ファイル.zip`

と実行しても本書の図5.5のような文字化けが再現できません。

また、解答にあるように

`$ ls | while read f; do echo -n $f : ; echo $f | nkf -g; done`

と実行しても

```
�|������a�m�����.txt :CP932
���[�+�[���.pdf :BINARY
秘密の圧縮ファイル.zip :UTF-8
```

と出力されます。

自分の環境が原因なのか、それともファイルが原因なのかがわからないので、お時間のあるときにチェックしていただけると幸いです。

**Comment by ryuichiueda** [comment]
情報ありがとうございます。OSのバージョンや、どの（仮想）環境上で動いているか、情報いただけますか？



> と実行しても本書の図5.5のような文字化けが再現できません。

こちらは、文字化けが起こらないのか、違う文字化けが起こるのかどちらでしょうか。

**Comment by keijinozaki** [comment]
返信有り難うございます。

私の環境は以下のとおりです。
仮想環境ではなくSSDにインストールしています。
OS: MX Linux 21.2.1
Kernel: 5.10.0-18-amd64
ロケール: en_US.UTF-8 および ja_JP.UTF-8 の両方で実行してみましたが、結果は同じでした


> こちらは、文字化けが起こらないのか、違う文字化けが起こるのかどちらでしょうか。

以下のように違う文字化けが起こります。

```
$ LANG=C unzip 秘密の圧縮ファイル.zip 
Archive:  秘密の圧縮ファイル.zip
 extracting: �|������a�m�����.txt  
  inflating: ���[�+�[���.pdf   

$ ls
''$'\364''|'$'\371\272\362\244\346\310\311''a'$'\304''m'$'\351\246\366\332\373\272''.txt'
''$'\351\312\374''['$'\351''+'$'\374''['$'\351\252\351\313''.pdf'
 秘密の圧縮ファイル.zip
```

**Comment by ryuichiueda** [comment]
ありがとうございます。本書ではUbuntuの場合だけサポートしていますので、ちょっとこれ以上調べられないかもしれませんが、またなにかわかったらこちらに書き込みます。
