### ISSUE TITLE
パソコン雑誌の記事を書かれている上田竜一さんへの質問です

### ISSUE THREAD

**Issue by takuyatahata** [shellgei/shellgei160#54]
@ryuichiueda  さんへ
上田竜一さんの記事を読んでいろいろと勉強しています。
出版された書籍は誤った操作の記述や誤植が多いので見つけたら逐一報告しようと思います。
ネット喫茶のパソコンを使用していますが、処理速度が遅くやりたいことができず、あきらめることが多いです。
主要なサービスはtwitterのアカウントが無いとほとんど何もできない状態で歯がゆい思いをしています。
古い携帯電話が故障中で直らないのでアカウントは作れません。

**Comment by ryuichiueda** [comment]
んーーーー。ちょっとissueでやることではないと思います。そして、私の名前は上田隆一ですので、他の書籍の誤植について非難する前に、ご自身のことを振り返っていただければと存じます。

**Comment by ryuichiueda** [comment]
見つけたら個別でissueいただければありがたくお受けいたします。私の名前は上田隆一です。

**Comment by takuyatahata** [comment]
どの雑誌か忘れましたが、間違って載っていた文字をそのまま覚えていて使ったのかもしれません。大変失礼しました。
issueがふさわしくないのであれば、また何か別の場所を紹介してください。
Shift-jisからUTFー８にコードを変換して文字化けを解消する記事を読みましたが、外字問題は中途半端で直していない人が多いですね。家庭用のコンピューターだと結構手間のかかる作業になります。
私の知り合いの樋田昌志さんのウェブサイトの漢訳の法華経です
[http://toyoda.tv/hokekyo.htm](url)
今、樋田さんはOCRで文字資料からデータを取り出してYOUTUBEの動画に起こしています。
結構、要領が悪いです。
プロで営利活動している人にあまり質問してはいけないのかもしれませんが、読者の感想を書きました。
