### ISSUE TITLE
問題9 ログの抽出の解答について

### ISSUE THREAD

**Issue by tena-beji** [shellgei/shellgei160#56]
問題文では、”2016年12月25日3時台の最初のログまでを出力”　となっていますが、解答例だと3時台のログすべてが出力されると思います。サンプルデータは1時間に1件のデータなので、問題文通りではありますが、問題文の条件は少なくとも1時間に1回はログがあるということなので、解答が正確ではないのかと思いました。ご確認いただけると幸いです。

**Comment by tena-beji** [comment]
別解2についてです。

**Comment by ryuichiueda** [comment]
そうですね。ご指摘ありがとうございます。

いまどうやって訂正するか考え中です。

**Comment by ryuichiueda** [comment]
`$ cat log_range.log | awk '$4" "$5>="[24/Dec/2016 21:00:00]" && $4" "$5<"[25/Dec/2016 03:59:60]" && a == 0;$4" "$5>"[25/Dec/2016 02:59:60]"{a++}'`

こういう感じで訂正を出しておきます。ありがとうございました！
