### ISSUE TITLE
PDF版p50誤植「自分秒」→「時分秒」

### ISSUE THREAD

**Issue by keisuke-nakata** [shellgei/shellgei160#57]
![image](https://github.com/shellgei/shellgei160/assets/6150143/8285347e-ce6c-479f-b6ab-f8da7403eec2)

ここはおそらく「時分秒」の誤植かと思われます。

**Comment by greymd** [comment]
こちら、ご反応が遅くなりました。
ご指摘の通りと思われますので [正誤表](https://github.com/shellgei/shellgei160#%E8%A8%82%E6%AD%A3) への反映をいたしました。

ご連絡ありがとうございました 🙇
