### ISSUE TITLE
問題3の別解1の2重バックスラッシュについて

### ISSUE THREAD

**Issue by mrsatomaru** [shellgei/shellgei160#63]
`grep -v ^\\.$`
でカレントディレクトリを表すエントリ . を除外していると理解しています．
そこで，私は以下でも良いと考えました．
`grep -v ^\.$`
しかしバックスラッシュ一つだと1桁の数字も除外されてしまいます．これはなぜでしょうか？
バックスラッシュ一つで「.」をエスケープできない理由がわかりません．
どなたか解説いただけると，大変ありがたいです．

**Comment by papiron** [comment]
ご質問について解答いたします。

ご認識の通り`grep -v ^\\.$`のコマンドはカレントディレクトリ`.`の行を除外します。
ここでご注意いただきたいのは、バックスラッシュはbashで特別な意味を持つ`|$#*?`などの特殊文字をエスケープする時に使う点です。
またバックスラッシュ自体を普通の文字として解釈するには、バックスラッシュでエスケープが必要です。

つまり`^\\.$`の2重バックスラッシュは、bashでエスケープ処理されて'^\.$'という正規表現になります。
echoコマンドで確かめてみると、分かりやすいと思います。
```
$ echo ^\\.$
^\.$
```
また`'^\.$'`や`"^\.$"`のように、シングルクォートやダブルクォートでクォーティングすると、特殊文字を普通の文字として解釈します。
```
$ echo '^\.$'
^\.$

$ echo "^\.$"
^\.$
```

**Comment by mrsatomaru** [comment]
理解できました．大変分かりやすい解説をありがとうございました．
