### ISSUE TITLE
練習 3.1.c \N は数字を表すメタ文字ではない

### ISSUE THREAD

**Issue by kariya-mitsuru** [shellgei/shellgei160#8]
PDF 版 P.129 で、

> Perl、Ruby、Pythonなどのモダンな言語の正規表現では、`\N`で数字を表すなど、メタ文字が充実しています。

との記載がありますが、Perl（PCRE）では `\N` は数字を表すメタ文字ではなく改行文字以外を表すメタ文字で、この記法は Ruby や Python には無いようです。

なお、完全に余談ですが Perl と Python 3.8 では `\N{name}` で Unicode 文字を名前で指定できるようです。

**Comment by ryuichiueda** [comment]
お手数かけます！これはたぶん\dの間違いです。確認して正誤表に掲載します。

**Comment by ryuichiueda** [comment]
正誤表に掲載しました。

https://github.com/shellgei/shellgei160/blob/master/README.md

**Comment by kariya-mitsuru** [comment]
あ、そちらに直されるのであれば P.127 の練習問題 10 行目（小問 5）も直された方が良いです。
（P.129 はそちらの解答なので）

**Comment by ryuichiueda** [comment]
あ、そうですね。何度もすみません。

**Comment by ryuichiueda** [comment]
p.127の修正も正誤表に追加しました。
