### ISSUE TITLE
練習 3.1.d 小問 2 の問題とその回答に小さな齟齬あり

### ISSUE THREAD

**Issue by kariya-mitsuru** [shellgei/shellgei160#9]
重箱の隅で恐縮ですが、小問 2 の問題は「東から始まりーで終わる文字列」となっているのですが、回答は「東京から始まりーで終わる文字列」になっています。

**Comment by ryuichiueda** [comment]
正誤表に掲載しました。ありがとうございます。

https://github.com/shellgei/shellgei160/blob/master/README.md

**Comment by ryuichiueda** [comment]
こちらcloseいたしますー。ありがとうございました。
